### ISSUE TITLE
CloudFormation stack failed to delete

### ISSUE THREAD

**Issue by KarlaLuciaYH** [aws-samples/mwaa-dashboard#1]
### Describe the bug
When deleting the stack, the state of the stack becomes `DELETE_FAILED` after almost one hour and a half.
<img width="1846" alt="image (2)" src="https://user-images.githubusercontent.com/63164164/181293755-1101e32d-152c-4f12-b12f-0ca04bef8289.png">

### Expected Behavior
State of the stack after deleting it: `DELETE_COMPLETE`

### Current Behavior
State of the stack after deleting it: `DELETE_FAILED`. This is  because CloudFormation did not receive a response from the Custom resource `SeedDynamoDB`.

### Reproduction Steps
```
aws cloudformation delete-stack --stack-name ${STACK_NAME}
```

### Possible Solution
After running the `delete-stack command` when the state is  `DELETE_FAILED`, run the following command:
 ```
aws cloudformation delete-stack --stack-name ${STACK_NAME} --retain-resources SeedDynamoDB
```

### Additional Information/Context
No response

**Comment by mrichman** [comment]
@KarlaLuciaYH Please get latest and give it a test. I fixed the issue where the SeedDynamoDB function would not delete. I also bumped the Python version to 3.9.

**Comment by carlosmontoyamoya** [comment]
Hi Mark, 
Thanks for your help, after downloading the repo’s latest version the stack deployed successfully with python 3.9 and the delete stack worked perfect. However, the step function started to fail during the evenbridge execution, it has an abnormal behaviour because sometimes it works and other times it does not. We modified the rule to 1 minute to check how it behaves and we got what is shown below:
![img01](https://user-images.githubusercontent.com/28406528/181381364-4d211efc-4ff7-40b4-9444-0626542fe12d.PNG)

It is raising this error when it fails just in the lambda used to generate the dashboard:
![image](https://user-images.githubusercontent.com/28406528/181381445-291b5005-6053-4ddc-8d52-21c5dda3d14e.png)

Below the StepFunction Log:
`{
  "version": "0",
  "id": "60507865-74bf-ccec-4583-3f4cebce9450",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "account",
  "time": "2022-07-27T20:24:54Z",
  "region": "us-east-1",
  "resources": [
    "arn:aws:events:us-east-1:account:rule/monitor-mwaa-environment-ariel-ScheduledRule-1X7DTYOOJCRK4"
  ],
  "detail": {},
  "CreateDashboardError": {
    "Error": "SchemaValidationError",
    "Cause": "{\"errorMessage\": \"Must contain a metric namespace.\", \"errorType\": \"SchemaValidationError\", \"requestId\": \"23250a1a-d5aa-467c-a582-eede73a11b57\", \"stackTrace\": [\"  File \\\"/var/task/aws_lambda_powertools/metrics/metrics.py\\\", line 186, in decorate\\n    self.__add_cold_start_metric(context=context)\\n\", \"  File \\\"/var/task/aws_lambda_powertools/metrics/metrics.py\\\", line 214, in __add_cold_start_metric\\n    is_cold_start = False\\n\", \"  File \\\"/var/lang/lib/python3.9/contextlib.py\\\", line 126, in __exit__\\n    next(self.gen)\\n\", \"  File \\\"/var/task/aws_lambda_powertools/metrics/metric.py\\\", line 119, in single_metric\\n    metric_set = metric.serialize_metric_set()\\n\", \"  File \\\"/var/task/aws_lambda_powertools/metrics/base.py\\\", line 188, in serialize_metric_set\\n    raise SchemaValidationError(\\\"Must contain a metric namespace.\\\")\\n\"]}"
  }
}
`

**Comment by mrichman** [comment]
Testing a change now. I'm going to let it run for a while, but so far no errors:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/11228/181392236-7a56127f-f01b-46cc-9714-9b399bd684e6.png">

**Comment by mrichman** [comment]
Please get latest and test. I ran a test overnight and adjusted some Lambda function timeouts.

**Comment by carlosmontoyamoya** [comment]
Hey Mark, 

We were monitoring the Step Function runs and now we are not having any problem. It seems it works perfect 👍 . 
![image](https://user-images.githubusercontent.com/28406528/181633754-60d0640d-6fa6-42f9-8341-b45fb7b028f1.png)

Thank you very much for helping us.

**Comment by mrichman** [comment]
Glad it's working for you. I appreciate the feedback!
